name = "Dinamik Fiyat Hesaplayıcı"
client_id = "ace3bfc493ea0b4df835573bd32b189d"
application_url = "https://dynamic-pricing-test-store.myshopify.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_themes,write_themes,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://dynamic-pricing-test-store.myshopify.com/auth/callback",
  "https://dynamic-pricing-test-store.myshopify.com/auth/shopify/callback",
  "https://dynamic-pricing-test-store.myshopify.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dynamic-pricing-test-store.myshopify.com"
