name = "Dinamik Fiyat Hesaplayıcı"
client_id = "your_client_id_here"
application_url = "https://your-app-domain.com"
embedded = true

[access_scopes]
# Read and write products
scopes = "read_products,write_products,read_themes,write_themes,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://your-app-domain.com/auth/callback",
  "https://your-app-domain.com/auth/shopify/callback",
  "https://your-app-domain.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "your-dev-store.myshopify.com"
